POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2EiLCJpZCI6IjY3NGIxMTM4Yzk3Y2Q3YTVhMGYwYzZkYyIsImlhdCI6MTczMjk4MDcwOH0.bFA0QoTCe6Wb-kWc_yVGVYN9UoErVEDoWI6kzfiqR4I

{
    "title": "Kuinka kaivaa koloja",
    "author": "Iha Ite",
    "url": "www.kaivuri.fi",
    "likes": 12345
}