PUT http://localhost:3003/api/blogs/674418e7f32287e2c1962305
Content-Type: application/json

{
    "title": "Kuinka veistää valtava vene",
    "author": "Nooa",
    "url": "www.jw.org",
    "likes": 234
}